-- =============================================================
-- KONSERVATORIYA ADMIN — Supabase schema + RLS
-- Run this in Supabase Dashboard → SQL Editor → New query
--
-- BEFORE RUNNING: replace YOUR_ADMIN_EMAIL_HERE below with your
-- actual admin email (the one you'll create in Auth → Users).
-- This script is idempotent — safe to re-run.
-- =============================================================


-- ─────────────────────────────────────────────────────────────
-- 1. Helper function: is the current request the admin?
--    >>>>> REPLACE 'admin@konservatoriya.uz' WITH YOUR EMAIL <<<<<
-- ─────────────────────────────────────────────────────────────
create or replace function public.is_admin()
returns boolean
language sql
security definer
stable
set search_path = public
as $$
  select coalesce(
    lower(auth.jwt() ->> 'email') = lower('admin@konservatoriya.uz'),
    false
  )
$$;

-- Lock down who can call this helper
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;


-- ─────────────────────────────────────────────────────────────
-- 2. NEWS table
-- ─────────────────────────────────────────────────────────────
create table if not exists public.news (
  id          bigint generated by default as identity primary key,
  title       text not null,
  category    text not null default 'Voqealar',
  date        date,
  excerpt     text,
  body        text,
  image       text,
  featured    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists news_created_at_idx on public.news (created_at desc);
create index if not exists news_category_idx on public.news (category);

alter table public.news enable row level security;

drop policy if exists "news_public_read"  on public.news;
drop policy if exists "news_admin_insert" on public.news;
drop policy if exists "news_admin_update" on public.news;
drop policy if exists "news_admin_delete" on public.news;

create policy "news_public_read"
  on public.news for select
  using (true);

create policy "news_admin_insert"
  on public.news for insert
  to authenticated
  with check (public.is_admin());

create policy "news_admin_update"
  on public.news for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "news_admin_delete"
  on public.news for delete
  to authenticated
  using (public.is_admin());


-- ─────────────────────────────────────────────────────────────
-- 3. POSTERS table (afishalar)
-- ─────────────────────────────────────────────────────────────
create table if not exists public.posters (
  id           bigint generated by default as identity primary key,
  title        text not null,
  artist       text,
  venue        text not null default 'Katta Zal',
  date         date,
  time         text,
  price        text,
  free         boolean not null default false,
  tags         text,
  description  text,
  image        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists posters_date_idx on public.posters (date);
create index if not exists posters_venue_idx on public.posters (venue);

alter table public.posters enable row level security;

drop policy if exists "posters_public_read"  on public.posters;
drop policy if exists "posters_admin_insert" on public.posters;
drop policy if exists "posters_admin_update" on public.posters;
drop policy if exists "posters_admin_delete" on public.posters;

create policy "posters_public_read"
  on public.posters for select
  using (true);

create policy "posters_admin_insert"
  on public.posters for insert
  to authenticated
  with check (public.is_admin());

create policy "posters_admin_update"
  on public.posters for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "posters_admin_delete"
  on public.posters for delete
  to authenticated
  using (public.is_admin());


-- ─────────────────────────────────────────────────────────────
-- 4. Auto-update updated_at trigger
-- ─────────────────────────────────────────────────────────────
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end
$$;

drop trigger if exists news_set_updated_at on public.news;
create trigger news_set_updated_at
  before update on public.news
  for each row execute function public.set_updated_at();

drop trigger if exists posters_set_updated_at on public.posters;
create trigger posters_set_updated_at
  before update on public.posters
  for each row execute function public.set_updated_at();


-- ─────────────────────────────────────────────────────────────
-- 5. STORAGE bucket for images
-- ─────────────────────────────────────────────────────────────
insert into storage.buckets (id, name, public)
values ('kons-media', 'kons-media', true)
on conflict (id) do update set public = true;

drop policy if exists "kons_media_public_read"   on storage.objects;
drop policy if exists "kons_media_admin_write"   on storage.objects;
drop policy if exists "kons_media_admin_update"  on storage.objects;
drop policy if exists "kons_media_admin_delete"  on storage.objects;

create policy "kons_media_public_read"
  on storage.objects for select
  using (bucket_id = 'kons-media');

create policy "kons_media_admin_write"
  on storage.objects for insert
  to authenticated
  with check (bucket_id = 'kons-media' and public.is_admin());

create policy "kons_media_admin_update"
  on storage.objects for update
  to authenticated
  using (bucket_id = 'kons-media' and public.is_admin())
  with check (bucket_id = 'kons-media' and public.is_admin());

create policy "kons_media_admin_delete"
  on storage.objects for delete
  to authenticated
  using (bucket_id = 'kons-media' and public.is_admin());


-- ─────────────────────────────────────────────────────────────
-- 6. Realtime — let the frontend subscribe to changes
-- ─────────────────────────────────────────────────────────────
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'news'
  ) then
    alter publication supabase_realtime add table public.news;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'posters'
  ) then
    alter publication supabase_realtime add table public.posters;
  end if;
end $$;


-- =============================================================
-- DONE. Now go to Auth → Users → "Add user" → enter the SAME
-- email you used in is_admin() above + a strong password.
-- (Recommended) Auth → Settings → disable public sign-ups.
-- =============================================================
