-- Ticker news (Bosh sahifa lentasi)
-- Run in Supabase Dashboard → SQL Editor

create table if not exists public.ticker_news (
  id          bigint generated by default as identity primary key,
  title       text not null,
  category    text default 'Yangilik',
  link        text,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists ticker_news_sort_idx on public.ticker_news (sort_order, created_at desc);

alter table public.ticker_news enable row level security;

drop policy if exists "ticker_public_read"   on public.ticker_news;
drop policy if exists "ticker_admin_insert"  on public.ticker_news;
drop policy if exists "ticker_admin_update"  on public.ticker_news;
drop policy if exists "ticker_admin_delete"  on public.ticker_news;

create policy "ticker_public_read"
  on public.ticker_news for select
  using (true);

create policy "ticker_admin_insert"
  on public.ticker_news for insert
  to authenticated
  with check (public.is_admin());

create policy "ticker_admin_update"
  on public.ticker_news for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "ticker_admin_delete"
  on public.ticker_news for delete
  to authenticated
  using (public.is_admin());

-- Auto-update updated_at
drop trigger if exists ticker_news_set_updated_at on public.ticker_news;
create trigger ticker_news_set_updated_at
  before update on public.ticker_news
  for each row execute function public.set_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'ticker_news'
  ) then
    alter publication supabase_realtime add table public.ticker_news;
  end if;
end $$;

notify pgrst, 'reload schema';
