-- Telegram posts (Yangiliklar sahifasidagi Telegram tab)
-- Run in Supabase Dashboard → SQL Editor

create table if not exists public.telegram_posts (
  id          bigint generated by default as identity primary key,
  post_url    text not null,
  caption     text,
  sort_order  int not null default 0,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists telegram_posts_sort_idx on public.telegram_posts (sort_order, created_at desc);

alter table public.telegram_posts enable row level security;

drop policy if exists "telegram_public_read"   on public.telegram_posts;
drop policy if exists "telegram_admin_insert"  on public.telegram_posts;
drop policy if exists "telegram_admin_update"  on public.telegram_posts;
drop policy if exists "telegram_admin_delete"  on public.telegram_posts;

create policy "telegram_public_read"   on public.telegram_posts for select using (true);
create policy "telegram_admin_insert"  on public.telegram_posts for insert to authenticated with check (public.is_admin());
create policy "telegram_admin_update"  on public.telegram_posts for update to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "telegram_admin_delete"  on public.telegram_posts for delete to authenticated using (public.is_admin());

drop trigger if exists telegram_posts_set_updated_at on public.telegram_posts;
create trigger telegram_posts_set_updated_at
  before update on public.telegram_posts
  for each row execute function public.set_updated_at();

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'telegram_posts'
  ) then
    alter publication supabase_realtime add table public.telegram_posts;
  end if;
end $$;

notify pgrst, 'reload schema';
