-- Foto galereya albomlari (admin paneldan boshqariladi)
-- Run in Supabase Dashboard → SQL Editor

create table if not exists public.gallery_albums (
  id          bigint generated by default as identity primary key,
  title       text not null,
  title_ru    text,
  title_en    text,
  category    text default 'Umumiy',
  album_date  date,
  cover       text,
  images      text[] not null default '{}'::text[],
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists gallery_albums_created_idx on public.gallery_albums (created_at desc);

alter table public.gallery_albums enable row level security;

drop policy if exists "gallery_public_read"  on public.gallery_albums;
drop policy if exists "gallery_admin_insert" on public.gallery_albums;
drop policy if exists "gallery_admin_update" on public.gallery_albums;
drop policy if exists "gallery_admin_delete" on public.gallery_albums;

create policy "gallery_public_read"
  on public.gallery_albums for select
  using (true);

create policy "gallery_admin_insert"
  on public.gallery_albums for insert
  to authenticated
  with check (public.is_admin());

create policy "gallery_admin_update"
  on public.gallery_albums for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "gallery_admin_delete"
  on public.gallery_albums for delete
  to authenticated
  using (public.is_admin());

-- Auto-update updated_at
drop trigger if exists gallery_albums_set_updated_at on public.gallery_albums;
create trigger gallery_albums_set_updated_at
  before update on public.gallery_albums
  for each row execute function public.set_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'gallery_albums'
  ) then
    alter publication supabase_realtime add table public.gallery_albums;
  end if;
end $$;

notify pgrst, 'reload schema';
