-- Videogalereya videolari (admin paneldan boshqariladi)
-- Run in Supabase Dashboard → SQL Editor

create table if not exists public.videos (
  id          bigint generated by default as identity primary key,
  title       text not null,
  title_ru    text,
  title_en    text,
  category    text default 'Umumiy',
  video_url   text not null,
  thumb       text,
  featured    boolean not null default false,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

create index if not exists videos_created_idx on public.videos (created_at desc);

alter table public.videos enable row level security;

drop policy if exists "videos_public_read"  on public.videos;
drop policy if exists "videos_admin_insert" on public.videos;
drop policy if exists "videos_admin_update" on public.videos;
drop policy if exists "videos_admin_delete" on public.videos;

create policy "videos_public_read"
  on public.videos for select
  using (true);

create policy "videos_admin_insert"
  on public.videos for insert
  to authenticated
  with check (public.is_admin());

create policy "videos_admin_update"
  on public.videos for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "videos_admin_delete"
  on public.videos for delete
  to authenticated
  using (public.is_admin());

-- Auto-update updated_at
drop trigger if exists videos_set_updated_at on public.videos;
create trigger videos_set_updated_at
  before update on public.videos
  for each row execute function public.set_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'videos'
  ) then
    alter publication supabase_realtime add table public.videos;
  end if;
end $$;

notify pgrst, 'reload schema';
