-- ─────────────────────────────────────────────────────────────
-- Online imtihonlar (Qabul bloki — Zoom orqali)
-- ─────────────────────────────────────────────────────────────

create table if not exists public.online_imtihonlar (
  id           bigint generated by default as identity primary key,
  nomi         text not null,
  nomi_ru      text,
  nomi_en      text,
  tavsif       text,
  tavsif_ru    text,
  tavsif_en    text,
  zoom_link    text not null,
  sana         date,
  vaqt         text,
  holat        text not null default 'faol',   -- 'faol' | 'yakunlangan' | 'kutilmoqda'
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists online_imtihonlar_sana_idx     on public.online_imtihonlar (sana);
create index if not exists online_imtihonlar_holat_idx    on public.online_imtihonlar (holat);
create index if not exists online_imtihonlar_sort_idx     on public.online_imtihonlar (sort_order);

alter table public.online_imtihonlar enable row level security;

drop policy if exists "online_imtihonlar_public_read"  on public.online_imtihonlar;
drop policy if exists "online_imtihonlar_admin_insert" on public.online_imtihonlar;
drop policy if exists "online_imtihonlar_admin_update" on public.online_imtihonlar;
drop policy if exists "online_imtihonlar_admin_delete" on public.online_imtihonlar;

create policy "online_imtihonlar_public_read"
  on public.online_imtihonlar for select
  using (true);

create policy "online_imtihonlar_admin_insert"
  on public.online_imtihonlar for insert
  to authenticated
  with check (public.is_admin());

create policy "online_imtihonlar_admin_update"
  on public.online_imtihonlar for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "online_imtihonlar_admin_delete"
  on public.online_imtihonlar for delete
  to authenticated
  using (public.is_admin());

-- Auto-update updated_at
drop trigger if exists online_imtihonlar_set_updated_at on public.online_imtihonlar;
create trigger online_imtihonlar_set_updated_at
  before update on public.online_imtihonlar
  for each row execute function public.set_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'online_imtihonlar'
  ) then
    alter publication supabase_realtime add table public.online_imtihonlar;
  end if;
end $$;
