-- ─────────────────────────────────────────────────────────────
-- Imtihon natijalari (Exam results files)
-- ─────────────────────────────────────────────────────────────

create table if not exists public.imtihon_natijalari (
  id           bigint generated by default as identity primary key,
  title        text not null,
  file_url     text not null,
  sana         date not null default current_date,
  sort_order   integer not null default 0,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists imtihon_natijalari_sana_idx on public.imtihon_natijalari (sana desc);
create index if not exists imtihon_natijalari_sort_idx on public.imtihon_natijalari (sort_order);

alter table public.imtihon_natijalari enable row level security;

drop policy if exists "imtihon_natijalari_public_read"  on public.imtihon_natijalari;
drop policy if exists "imtihon_natijalari_admin_insert" on public.imtihon_natijalari;
drop policy if exists "imtihon_natijalari_admin_update" on public.imtihon_natijalari;
drop policy if exists "imtihon_natijalari_admin_delete" on public.imtihon_natijalari;

create policy "imtihon_natijalari_public_read"
  on public.imtihon_natijalari for select
  using (true);

create policy "imtihon_natijalari_admin_insert"
  on public.imtihon_natijalari for insert
  to authenticated
  with check (public.is_admin());

create policy "imtihon_natijalari_admin_update"
  on public.imtihon_natijalari for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "imtihon_natijalari_admin_delete"
  on public.imtihon_natijalari for delete
  to authenticated
  using (public.is_admin());

-- Auto-update updated_at
drop trigger if exists imtihon_natijalari_set_updated_at on public.imtihon_natijalari;
create trigger imtihon_natijalari_set_updated_at
  before update on public.imtihon_natijalari
  for each row execute function public.set_updated_at();

-- Realtime
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'imtihon_natijalari'
  ) then
    alter publication supabase_realtime add table public.imtihon_natijalari;
  end if;
end $$;

-- Seed existing hardcoded data
insert into public.imtihon_natijalari (title, file_url, sana, sort_order)
values 
  ('Cholgʻu ijrochiligi: Xalq cholgʻulari (Chang)', '/pdf/imtihon-natijalari/cholgu_ijrochiligi_xalq_cholgulari_chang.pdf', '2026-07-06', 0),
  ('Cholgʻu ijrochiligi: Xalq cholgʻulari (Nay, Qoʻshnay, Bayan, Akkordeon)', '/pdf/imtihon-natijalari/cholgu_ijrochiligi_xalq_cholgulari_nay_koshnay_bayan_akardeon.pdf', '2026-07-06', 1),
  ('Cholgʻu ijrochiligi: Torli cholgʻular (Skripka, Alt) (Oʻzbek)', '/pdf/imtihon-natijalari/cholgu_ijrochiligi_torli_cholgular_skripka_alt_ozbek.pdf', '2026-07-06', 2)
on conflict do nothing;
